/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Day10;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThuyVT
 */
public class QLGB extends javax.swing.JFrame {

    List<GiuongBenh> listGb = new ArrayList<>();
    DefaultTableModel defaultTable = new DefaultTableModel();

    /**
     * Creates new form QLGB
     */
    public QLGB() {
        initComponents();

        // tạo kết nối DefaultTableModel và table
        defaultTable = (DefaultTableModel) tblGiuongBenh.getModel();
        // tạo danh sách mặc định
        listMacDinh(listGb);
        // đổ dữ liệu danh sách lên bảng
        hienThiLenBang(listGb);
        // hiển thị thông tin đối tượng thứ 4
        // index = 3
        hienThiLenForm(listGb.get(3));
    }

    // tạo danh sách mặc dịnh
    public void listMacDinh(List<GiuongBenh> danhSach) {
        // Combo box: Bac si CKI, Bac si CKII, Pho khoa, Truong khoa
        danhSach.add(new GiuongBenh("A", 12, "L303", 2, "thuy", "Bac si CKI",
                true, "Khoa ngoai", 1200000, 10));
        danhSach.add(new GiuongBenh("B", 2, "F103", 3, "minh", "Pho khoa",
                false, "Khoa noi", 112222, 7));
        danhSach.add(new GiuongBenh("C", 3, "T201", 5, "thien", "Truong khoa",
                false, "Khoa ngoai", 15333, 2));
        danhSach.add(new GiuongBenh("D", 4, "P303", 6, "loan", "Bac si CKII",
                false, "Khoa san", 11000, 3));
//        danhSach.add(new GiuongBenh("E", 7, "H310", 10, "mai", "Bac si CKI",
//                true, "Khoa noi", 97628, 2));
    }

    // hiển thị danh sách lên bảng
    public void hienThiLenBang(List<GiuongBenh> danhSach) {
        // reset bảng về 0
        defaultTable.setRowCount(0);
        for (GiuongBenh gb : danhSach) {
            defaultTable.addRow(new Object[]{
                gb.getTenBN(),
                gb.getMaBN(),
                gb.getSoPhong(),
                gb.getSoGiuong(),
                gb.getTenBS(),
                gb.getChucVu(),
                gb.isVip(),
                gb.getKhoa(),
                gb.getTien(),
                gb.getSoNgay()
            });
        }
    }

    // hiển thị đối tượng lên form
    public void hienThiLenForm(GiuongBenh gb) {
        txtTenBN.setText(gb.getTenBN());
        txtMaBN.setText(String.valueOf(gb.getMaBN()));
        txtBacSi.setText(gb.getTenBS());
        cboChucVu.setSelectedItem(gb.getChucVu());
        chkVip.setSelected(gb.isVip());
        if (gb.getKhoa().equalsIgnoreCase("Khoa noi")) {
            rdoKhoaNoi.setSelected(true);
        } else if (gb.getKhoa().equalsIgnoreCase("Khoa ngoai")) {
            rdoKhoaNgoai.setSelected(true);
        } else if (gb.getKhoa().equalsIgnoreCase("Khoa san")) {
            rdoKhoaSan.setSelected(true);
        }
        txtTien.setText(String.valueOf(gb.getTien()));
        txtSoNgay.setText(String.valueOf(gb.getSoNgay()));
        txtSoGiuong.setText(String.valueOf(gb.getSoGiuong()));
        txtSoPhong.setText(gb.getSoPhong());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenBN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoPhong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoGiuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBacSi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboChucVu = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        chkVip = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        rdoKhoaNoi = new javax.swing.JRadioButton();
        rdoKhoaNgoai = new javax.swing.JRadioButton();
        rdoKhoaSan = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtTien = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSoNgay = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGiuongBenh = new javax.swing.JTable();
        btnGhi = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ GIƯỜNG BỆNH");

        jLabel2.setText("Tên bệnh nhân");

        jLabel3.setText("Mã bệnh nhân");

        jLabel4.setText("Số phòng");

        jLabel5.setText("Số giường");

        jLabel6.setText("Tên bác sĩ");

        jLabel7.setText("Chức vụ");

        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bac si CKI", "Bac si CKII", "Pho khoa", "Truong khoa" }));

        jLabel8.setText("Vip");

        chkVip.setText("Vip");
        chkVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVipActionPerformed(evt);
            }
        });

        jLabel9.setText("Khoa");

        buttonGroup1.add(rdoKhoaNoi);
        rdoKhoaNoi.setSelected(true);
        rdoKhoaNoi.setText("Khoa noi");

        buttonGroup1.add(rdoKhoaNgoai);
        rdoKhoaNgoai.setText("Khoa ngoai");

        buttonGroup1.add(rdoKhoaSan);
        rdoKhoaSan.setText("Khoa san");

        jLabel10.setText("Tiền");

        jLabel11.setText("Số ngày");

        tblGiuongBenh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên BN", "Mã BN", "Số phòng", "Số giường", "Tên BS", "Chức vụ", "Vip", "Khoa", "Tiền", "Số ngày"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblGiuongBenh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGiuongBenhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGiuongBenh);

        btnGhi.setText("Ghi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnDoc.setText("Đọc");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenBN, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkVip)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(rdoKhoaNoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoKhoaNgoai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdoKhoaSan))
                            .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGhi)
                            .addComponent(btnDoc))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGhi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chkVip)
                    .addComponent(jLabel9)
                    .addComponent(rdoKhoaNoi)
                    .addComponent(rdoKhoaNgoai)
                    .addComponent(rdoKhoaSan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtSoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVipActionPerformed

    private void tblGiuongBenhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGiuongBenhMouseClicked
        // TODO add your handling code here:
        int rowIndex = tblGiuongBenh.getSelectedRow();
        if (rowIndex >= 0) {
            hienThiLenForm(listGb.get(rowIndex));
        }
    }//GEN-LAST:event_tblGiuongBenhMouseClicked

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        // TODO add your handling code here:
        if (listGb.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách trống");
        } else {
            String mes = new GBService().ghiFile("giuongbenh.txt", listGb);
            JOptionPane.showMessageDialog(this, mes);
        }
    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        // TODO add your handling code here:
        String mes = new GBService().docFile("giuongbenh.txt", listGb);
        JOptionPane.showMessageDialog(this, mes);
        if (mes.equalsIgnoreCase("Đọc file thành công")) {
            hienThiLenBang(listGb);
            System.out.println("danhSach hiển thị:" + listGb.size());

        }
    }//GEN-LAST:event_btnDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLGB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JCheckBox chkVip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoKhoaNgoai;
    private javax.swing.JRadioButton rdoKhoaNoi;
    private javax.swing.JRadioButton rdoKhoaSan;
    private javax.swing.JTable tblGiuongBenh;
    private javax.swing.JTextField txtBacSi;
    private javax.swing.JTextField txtMaBN;
    private javax.swing.JTextField txtSoGiuong;
    private javax.swing.JTextField txtSoNgay;
    private javax.swing.JTextField txtSoPhong;
    private javax.swing.JTextField txtTenBN;
    private javax.swing.JTextField txtTien;
    // End of variables declaration//GEN-END:variables
}
